language: node_js
node_js:
 - 10.15.3
cache: npm

before_install:
install:
  - yarn
script:
  - yarn test
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on: 
    branch: master



